on:
  push:
    branches:
      - master

name: Build tModLoader and upload

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        run: |
          docker build --target linux/amd64 --build-arg UID=1001 --build-arg GID=1001 -t tmodloader:latest .
      - name: Export
        run: |
          docker save tmodloader:latest -o tmodloader.tar
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: ./tmodloader.tar
          target: /home/${{ secrets.USER }}
          